Repository pranjal36/pranjal36, pull requests merged in 2022-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#2 Added information & features (trophie stats)
  README.md
Labels: enhancement, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#3 Added more info
  README.md
Labels: documentation, enhancement, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest
